### ISSUE TITLE
JSON invalid output

### ISSUE THREAD

**Issue by pascalin** [PhilosophyHubio/kw_extractor#1]
Attempts at reading JSON files with Python throws a json.decoder.JSONDecodeError.

>>> import json
>>> with open("storage/SV8SV79P/PNAS-2009-Ayala-10033-9_kw.json") as data:
...     kwds = json.load(data)
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Comment by ipardogranillo** [comment]
This should be solved first as it is considered a major bug

**Comment by ipardogranillo** [comment]
Executing this debugging block:

```
open(out_full_path,"w").write(payload)
with open(out_full_path) as data:
    print(json.load(data))
```

yielded:    

{'id': '23AF2PMD', 'keywords': [['THE', 0.0003581098937378261], ['and', 0.0012114963482277817], ['Homo', 0.0023383046406748615], ['that', 0.002378336352566454], ['and the', 0.0026556370438984003], ['the ALL', 0.0027387080191625265], ['the sister', 0.0027583972558142523], ['the Homo', 0.002893246354140625], ['GARHI', 0.0029780750605328974], ['ALL TAXA', 0.0032192751326510284], ['AUSTRALOPITHECUS GARHI', 0.0033390489197980384], ['that the', 0.003502059466127088], ['species', 0.003665408869223107], ['the Bouri', 0.003678652129157631], ['STRAIT', 0.003708141928850378], ['the genus', 0.004452473497141356], ['AUSTRALOPITHECUS', 0.004784027113590811], ['All', 0.005338261793411279], ['the species', 0.005722558065261057], ['from the', 0.005728148773692349], ['genus Homo', 0.006390089236427345], ['taxa', 0.006477563255623978], ['Strait and', 0.006760403490542639], ['the relationships', 0.006863587552933752], ['the phylogenetic', 0.007622025677786843], ['are', 0.007753281938668361], ['TAXA analysis', 0.007951462870200154], ['figure', 0.00822859432097792], ['with the', 0.008644548218039921], ['from', 0.008996800093730242], ['hominid', 0.009248506695720752], ['new', 0.009314128100584837], ['and Grine', 0.009590405736758904], ['analysis', 0.009762676826938042], ['garhi and', 0.009954929477292951], ['The present', 0.01065046304672452], ['with', 0.011199059660004793], ['hominid species', 0.011843058487575296], ['the Omo', 0.01189785899173283], ['the new', 0.012113095332903117], ['the character', 0.012147851240473942], ['this', 0.01252550954406178], ['sister taxon', 0.012551851734030813], ['sister', 0.012733596857188199], ['new species', 0.01276174139818941], ['These', 0.013043030575997268], ['the other', 0.013468824536066805], ['Homo species', 0.013650398075629977], ['GRINE', 0.013930467442661227], ['early Homo', 0.014128126166764357], ['Homo clade', 0.014250646537375384], ['Bouri skull', 0.014496170851381572], ['Asfaw', 0.014660094539133209], ['ramidus', 0.014696960344854048], ['anamensis', 0.014776816452712702], ['hominids', 0.014797610713153204], ['because the', 0.01533450126819472], ['genus', 0.01576118805639901], ['Ludus Vitalis', 0.01595802097112041], ['Paranthropus', 0.016174039548929844], ['species are', 0.01666787022235304], ['Bouri', 0.01680772058241323], ['and Homo', 0.0169221635256756], ['would', 0.017137879789997756], ['the first', 0.017225049350571994], ['the fossil', 0.017301890475327413], ['taxon', 0.01740802650835981], ['the hypothesis', 0.017479380967635655], ['the GARHI', 0.01769342835357913], ['characters', 0.018005476006215465], ['character', 0.0187883227890944], ['relationships', 0.019361482918147193], ['other', 0.01957310378884507], ['the only', 0.02001326355854544], ['not', 0.02014817570699731], ['the most', 0.02014971252765226], ['New York', 0.020252135956361904], ['the hominid', 0.02058322032837532], ['skull', 0.02139985611253698], ['these species', 0.022120490494991284], ['was the', 0.022176764413666467], ['africanus', 0.02294538646617388], ['only', 0.02314452131343495], ['and STRAIT', 0.023661412216899238], ['and thus', 0.023715919838419725], ['early', 0.023751624344862866], ['all hominids', 0.023790437403120625], ['the analysis', 0.02414052539652215], ['The trees', 0.024204456854111808], ['the results', 0.02422564336869107], ['sister taxa', 0.024685506495032], ['only the', 0.0250165794481818], ['from that', 0.025137725915018415], ['the original', 0.02527655312247856], ['fossil', 0.025733016922926434], ['the three', 0.025949960143245496], ['and Collard', 0.026047455461331755], ['ramidus and', 0.02632199950614149], ['White', 0.026514203064143628], ['early hominid', 0.02662544106522237]]}

or similar results for each of the processed files.

---

Expect a new commit soon
